dof-dss/nicsdru_unity

config/uregni/config/core.base_field_override.node.news.status.yml
config/uregni/config/field.storage.node.body.yml
config/uregni/config/field.storage.node.field_photo.yml
config/uregni/config/field.storage.node.field_published_date.yml

Not entirely sure why the langcode is changing in the field.storage yml files. Seems to change after a migration.

Changing the published status of news and field storage modifications

---

config/uregni/config/core.entity_form_display.node.consultation.default.yml
config/uregni/config/core.entity_form_display.node.news.default.yml
config/uregni/config/core.entity_form_display.node.publication_page.default.yml
config/uregni/config/core.entity_view_display.node.consultation.default.yml
config/uregni/config/core.entity_view_display.node.consultation.teaser.yml
config/uregni/config/core.entity_view_display.node.news.default.yml
config/uregni/config/core.entity_view_display.node.news.teaser.yml
config/uregni/config/core.entity_view_display.node.publication_page.default.yml
config/uregni/config/core.entity_view_display.node.publication_page.teaser.yml
config/uregni/config/field.field.node.consultation.field_meta_tags.yml
config/uregni/config/field.field.node.news.field_meta_tags.yml
config/uregni/config/field.field.node.publication_page.field_meta_tags.yml
config/uregni/config/field.storage.node.field_meta_tags.yml
config/uregni/config/pathauto.pattern.consultations_pattern.yml
config/uregni/config/pathauto.pattern.news_pattern.yml
config/uregni/config/pathauto.pattern.publications_pattern.yml

Tidying the 3 content types I've been working on (News, Publications, Consultations)
- I've added a metatag field and applied it to the 3 content types.
- I've added pathauto patterns for all 3 content types.
- There is a URL redirect field added in from enabling the redirect module in D8UN-redirect-settings

Adding metatag and pathauto settings for News/Publications/Consultations

---

config/uregni/config/core.entity_form_display.node.consultation.default.yml
config/uregni/config/core.entity_form_display.node.news.default.yml
config/uregni/config/core.entity_view_display.node.consultation.default.yml
config/uregni/config/core.entity_view_display.node.news.default.yml
config/uregni/config/core.entity_view_display.node.publication_page.default.yml
config/uregni/config/field.field.node.consultation.body.yml
config/uregni/config/field.field.node.consultation.field_summary.yml
config/uregni/config/field.field.node.news.body.yml
config/uregni/config/field.field.node.publication_page.body.yml
config/uregni/config/field.storage.node.field_summary.yml

Tidying up content types News/Publications/Consultations after sprint review yesterday
- Changing body yml to use single quotes.
- Changing summary field on consultations to use text plain long to keep in line with D7
- Moving the teaser field in form displays to match D7
- Disabling the links field from view displays.
- Setting consultations to use datetime_range as it should be.

D8 un tidy content types

---

config/uregni/config/core.entity_form_display.node.page.default.yml
config/uregni/config/core.entity_view_display.node.page.default.yml
config/uregni/config/core.entity_view_display.node.page.teaser.yml
config/uregni/config/field.field.node.page.body.yml
config/uregni/config/field.field.node.page.field_meta_tags.yml
config/uregni/config/pathauto.pattern.basic_page_pattern.yml

Add meta tag field to basic page content type and add pathauto pattern for basic page (and other content types that have the same 'default' pattern.

Updated basic page config export

---

config/uregni/config/system.menu.account.yml
config/uregni/config/system.menu.admin.yml
config/uregni/config/system.menu.main.yml
config/uregni/config/system.menu.menu-footer-links.yml
config/uregni/config/system.menu.menu-useful-links.yml
config/uregni/config/system.menu.tools.yml

Updates to the site menus following migrate import of upgrade_menu_settings and upgrade_d7_menu. I am unable to delete the footer menu as it is a default menu. 
I can't place the main menu block in the appropriate region yet, as outlined in the Jira task, as the theme has not been set.

D8UN-16 Menu config

---

config/uregni/config/facets.facet.topic.yml
config/uregni/config/facets.facet.topic_consultation.yml
config/uregni/config/search_api.index.consultations.yml
config/uregni/config/search_api.index.publications.yml
config/uregni/config/structure_sync.data.yml
config/uregni/config/views.view.publications_search.yml

- Taxonomy terms selected from the topic facet displayed a taxonomy label. I've added the topic field as an integer to the index and amended the facet to use this field, transforming it to term + id.
- Homepage blocks have a link to the publications topics so I have amended these to use the new term + id path.

Taxonomy urls

---

config/uregni/config/core.entity_form_display.node.news.default.yml
config/uregni/config/core.entity_form_display.node.page.default.yml
config/uregni/config/core.entity_form_display.node.publication_page.default.yml
config/uregni/config/core.entity_form_display.node.staff_member.default.yml
config/uregni/config/core.entity_form_display.node.vacancy.default.yml
config/uregni/config/core.entity_view_display.node.news.default.yml
config/uregni/config/core.entity_view_display.node.news.teaser.yml
config/uregni/config/core.entity_view_display.node.page.default.yml
config/uregni/config/core.entity_view_display.node.publication_page.default.yml
config/uregni/config/core.entity_view_display.node.staff_member.default.yml
config/uregni/config/core.entity_view_display.paragraph.map.default.yml
config/uregni/config/core.entity_view_display.paragraph.map.embed.yml
config/uregni/config/core.entity_view_display.paragraph.map.preview.yml
config/uregni/config/field.field.node.news.field_photo.yml
config/uregni/config/field.field.node.page.field_page_top_image.yml
config/uregni/config/field.field.node.publication_page.field_publication_image.yml
config/uregni/config/field.field.node.staff_member.field_member_image.yml
config/uregni/config/field.storage.node.field_member_image.yml
config/uregni/config/field.storage.node.field_page_top_image.yml
config/uregni/config/field.storage.node.field_photo.yml
config/uregni/config/field.storage.node.field_publication_image.yml
config/uregni/config/views.view.publications_search.yml
web/sites/uregni/themes/uregni_theme/package.json

- Changing the image field to use an entity reference media field to match NIDirect.
- Updated displays to include new entity reference media fields.
- D8UN-98-responsive-images needs approval before image styles can be updated properly.
- Updated nicsdru_unity_theme package.
- Added in lingering config files, seem to just be updates to structure i.e. 1 - true, 0 - false.

Changing image fields to an entity reference field

---

config/uregni/config/views.view.publications_search.yml

The Publications menu link has moved so I'm adding it back under About us.

Adding publications menu link as a child of About us

---

config/uregni/config/block.block.sidemenu.yml

Having the sidebar menu enabled for Board member is adding a blank block and affecting the styling. removing the content type from config fixes this.

Removing board member content type from using sidebar menu

---

.circleci/config.yml

Bug fix to the Unity edge build which has been failing on config import for the last few days

clear cache before config import

---

config/uregni/config/user.role.author_user.yml

Without this permission, authors could not view their own drafts or send them to review.

D8UN-334 Give authors permission to view the latest version

---

.platform.app.yaml

To speed up deployments, we should only run these commands for sites that are live or are currently being worked on.

reduce number of sites deployed

---

.circleci/config.yml

Attempt to resolve a consistent error in the overnight build "an activity is currently pending or in progress" simply by changing the timing.

adjust timing of edge build deploy

---

config/odscni/config/core.entity_view_display.media.image.media_library.yml
web/modules/custom/unity_common/unity_common.module

Origins media module attaches a custom library to the media view from nicsdru_origins_theme. We don't have direct access to that in unity so I have replicated the code from origins_media and attached a custom library from nicsdru_unity_theme.

Attaching custom styles to the media library view

---

config/fiscalcommissionni/config/views.view.evidence_search.yml

There is a bug on the Evidence search of the Fiscal Commission site, this will fix it

Fiscal Comm: Change filter identifier on Consultations search

---

.circleci/config.yml

At the moment, running these tests just adds 6 minutes to every build, we can reinstate this step if we do start to write tests

turn off unit tests for Unity as there aren't any

---

.lando/scripts/appserver_build.sh

Causes confusion and possibly provisioning headaches based on experiences by myself and @ooneill547 this week. Prestissimo is no longer needed as composer 2 supports concurrent downloads whereas composer 1 did not.

Remove prestissimo; redundant with composer 2

---

.circleci/config.yml

Turns out you get an odd bootstrap error without this.

Substituting single quote for double quotes around drush command

---

config/independentreviewofeducation/config/config_ignore.settings.yml

We don't want the social media config to be overwritten on a deployment so adding the settings in to be ignored.

Config ignore settings for social media links

---

.platform/routes.yaml

Remove explicit routes for attorney general and policing board as sites are now fully live

Post release route tidying

---

.circleci/config.yml

- Removes custom nodejs install with nvm as node 14 already bundled in the docker image.
- Shunt some common env vars into the docker yml fragment, for brevity.

Fix edge build on CI

---

.circleci/config.yml

Some minor shuffling of YAML blocks, but pretty much reinstate last convenience image for this job as the new images have some internal differences that mean npm doesn't have every system package or tool available to it to successfully compile the SASS code.
Future work aims to standardise on, I believe, node 16 which means we can review this job again at a point where it either develops problems or we can take an easier upgrade route.

Reinstate past convenience image with custom theme compilation steps

---

composer.json
composer.lock

As per @johangant comment "Noted from discussion with @soda736 today that this PR might now be superseded by upstream changes. Providing honeypot's at least version 2.1 this PR can be closed 👍" on PR https://github.com/dof-dss/nicsdru_unity/pull/1450
Updating honeypot so his PR can be closed.

Updating honeypot module

---

.circleci/config.yml
.lando.base.yml
build-themes.sh

Usage examples:
- `./build-themes.sh` build all site themes with default sites dir of /app/project/sites
- `./build-themes.sh --sites-dir $PROJECT_ROOT/project/sites --site-names uregni,octf` build two sites with overridden sites-dir variable
By varying the parameters you can build some/all themes on Lando or in Circle CI containers which have a different internal site path

Adjust rebuild theme script to take two optional params for sites dir and names

---

.lando.base.yml
.lando/scripts/appserver_build.sh

- Means no more 20 seconds, followed by 60 second warning message on every application rebuild.
- Pruned away yarn. Can't see anything we use that exclusively relies on that and isn't compatible with npm

Install legacy npm version using newer installer script

---

.lando.base.yml

To evaluate:
- Checkout this branch
- `lando rebuild -y`
- Find a suitable site theme folder.
- `rm -rf node_modules`
- `lando npm install`
- `lando npm run build`
If you end up with a suitable node_modules folder and can generate *.css files, then this works for you. If not, it might be an out of date dependency in a package.json file (check a recent theme) or if a compilation error, you should check if you have the `CPPFLAGS` env var present as this permits cross-chip compilation for any older npm packages that don't have pre-existing binaries ready to fetch.

Shift front-end tooling out of appserver container into own

---

project/config/uregni/config/pathauto.pattern.basic_page_pattern.yml
project/config/uregni/config/pathauto.pattern.vacancy.yml
project/config/uregni/config/pathauto.pattern.vacancy_pattern.yml

- Bug found when adding vacancy content types - if 'admin' or 'administrive' was in the URL it would cause forbidden error. - With /vacancy/title pattern, issue is solved.

URL Pattern for Vacancy

---

.circleci/config.yml
.circleci/workflow-config.yml
.ddev/commands/web/phpcs
phpcs.sh

- Bulk of jobs/commands now sourced from https://github.com/dof-dss/webdev-ci/blob/development/shared-config.yml for re-use across Unity repos.
- Workflows for this project defined under `.circleci/workflow-config.yml `
- CI setup and continue tasks (via orbs) defined in `.circleci/config.yml`
Job names have changed (a bit) so a repo admin will need to amend branch protection rules to unselect the old and select the new CI job names required to permit a PR to merge.

Centralised CI config improvements
