- .circleci/config.yml
- Replace origins profile reference with minimal to allow install from config
> Fix CI breakage

- composer.json
- composer.lock
Does what it says on the tin :)
> Swap out origins theme for unity theme

- README.md
- imports/data/README.md
- imports/files/sites/README.md
Improve README to include instructions for migrating files from D7.
> Migration improvements

- config/uregni/config/core.entity_form_display.node.staff_member.default.yml
- config/uregni/config/core.entity_view_display.node.staff_member.default.yml
- config/uregni/config/core.entity_view_display.node.staff_member.teaser.yml
- config/uregni/config/field.field.node.staff_member.field_member_image.yml
- config/uregni/config/field.field.node.staff_member.field_member_role.yml
- config/uregni/config/field.field.node.staff_member.field_metatag.yml
- config/uregni/config/field.storage.node.field_member_image.yml
- config/uregni/config/field.storage.node.field_member_role.yml
- config/uregni/config/field.storage.node.field_metatag.yml
- config/uregni/config/field.storage.user.field_metatag.yml
- config/uregni/config/pathauto.pattern.board_member_pattern.yml
Board Member field changes config files
> board member field config

- config/uregni/config/block.block.mainpagecontent.yml
- config/uregni/config/block.block.pagetitle.yml
- config/uregni/config/core.extension.yml
Enabling the uregni sub-theme and placing the Page title and Main page content blocks.
> D8 un 15 create subtheme

- config/uregni/config/core.base_field_override.node.vacancy.promote.yml
- config/uregni/config/core.base_field_override.node.vacancy.status.yml
- config/uregni/config/core.base_field_override.node.vacancy.title.yml
- config/uregni/config/core.date_format.uregni_long.yml
- config/uregni/config/core.entity_form_display.node.vacancy.default.yml
- config/uregni/config/core.entity_view_display.node.vacancy.default.yml
- config/uregni/config/core.entity_view_display.node.vacancy.teaser.yml
- config/uregni/config/field.field.node.vacancy.field_appointment.yml
- config/uregni/config/field.field.node.vacancy.field_closing_date.yml
- config/uregni/config/field.field.node.vacancy.field_meta_tags.yml
- config/uregni/config/field.field.node.vacancy.field_salary.yml
- config/uregni/config/field.field.node.vacancy.field_vacancy_attachments.yml
- config/uregni/config/field.storage.node.field_appointment.yml
- config/uregni/config/field.storage.node.field_closing_date.yml
- config/uregni/config/field.storage.node.field_salary.yml
- config/uregni/config/field.storage.node.field_vacancy_attachments.yml
- config/uregni/config/language.content_settings.node.vacancy.yml
- config/uregni/config/node.type.vacancy.yml
- Content type/form/display settings fo vacancy content type.
- Added the metatag field to vacancy.
- I added a Uregni long date format for the vacancy closing date.
> D8 un 43 44 vacancy migration

- config/uregni/config/field.field.node.news.body.yml
- config/uregni/config/field.field.node.vacancy.body.yml
Making 2 changes to config after completing the full migration.
> D8 un 67 migration full

- .platform.app.yaml
- reinstate site install loop (was withdrawn before with Yaml syntax problems)
> implement site loop in Yaml

- composer.lock
Updated drupal core to the recommended 8.8.8 and did a blanket update on all contrib modules.
> Core and module updates

- config/uregni/config/core.entity_form_display.media.document.default.yml
- config/uregni/config/core.entity_form_display.media.document.media_library.yml
- config/uregni/config/core.entity_view_display.media.document.default.yml
- config/uregni/config/core.entity_view_display.media.document.embed.yml
- config/uregni/config/core.entity_view_display.media.document.media_library.yml
- config/uregni/config/field.field.media.document.field_media_file.yml
- config/uregni/config/language.content_settings.media.document.yml
- config/uregni/config/media.type.document.yml
Document media type config seemed to be missing.
> D8 un 20 entity browser documents

- config/uregni/config/core.extension.yml
- config/uregni/config/facets.facet.type.yml
- config/uregni/config/search_api.index.publications.yml
- web/sites/uregni/modules/custom/uregni_publications/uregni_publications.info.yml
- web/sites/uregni/modules/custom/uregni_publications/uregni_publications.module
- I've created a uregni_publications module to add a result count to the header of the Publication search page. After discussion yesterday, this may need moved into a global unity_search module as most Unity sites will share this functionality.
- Also changed the indexed title to use fulltext:edge.
- Changed the Type facet to use the label instead of machine name.
> D8 un 50 publications solr index

- config/uregni/config/block.block.exposedformnews_searchnews_search_page.yml
- config/uregni/config/block.block.publisheddate.yml
- config/uregni/config/core.extension.yml
- config/uregni/config/facets.facet.published_date.yml
- config/uregni/config/facets.facet_source.search_api__views_page__news_search__news_search_page.yml
- config/uregni/config/views.view.news_search.yml
- web/modules/custom/unity_search_pages/unity_search_pages.info.yml
- web/modules/custom/unity_search_pages/unity_search_pages.module
I took Adam's uregni_publications module and made it unity_search_pages. There is probably still a good bit of work to make it more universal for all unity sites.
Created the news search view and date published facet.
> D8UN-53 Implement News search

- web/sites/settings.lando.php
- web/sites/site.settings.php
It's common to all environments so makes sense to store here.
> Move HASH_SALT setting into general site settings file

- web/sites/uregni/themes/uregni_theme/templates/layout/page--news.html.twig
- web/sites/uregni/themes/uregni_theme/templates/layout/page--publications.html.twig
- web/sites/uregni/themes/uregni_theme/templates/layout/page--search.html.twig
Adding the page title to view pages. Placed the block here to be above breadcrumbs when they are implemented at later stage.
> Adding page title to view pages

- config/uregni/config/core.extension.yml
- web/modules/custom/unity_common/unity_common.info.yml
- web/modules/custom/unity_common/unity_common.module
Create unity_common module and add instructional text to linkit editor dialogue form
> D8UN-76 Add text to linkit editor dialogue form

- config/uregni/config/system.site.yml
Setting homepage in config as deployments seem to unset it each time.
> Setting site homepage

- web/sites/uregni/themes/uregni_theme/uregni_theme.info.yml
Update path to ckeditor.css and remove uregni specific styles library link
> Update file paths uregni

- composer.lock
Getting the error `[ErrorException] Undefined index: extra` when trying to run `composer require` or `composer remove`. 
Based on information from https://github.com/composer/composer/issues/8047 it seems that this was caused by an issue with composer-drupal-optimizations module after a symfony update. 
The fix was found here: https://github.com/zaporylie/composer-drupal-optimizations/pull/22
> Update composer-drupal-optimizations to fix an error

- config/uregni/config/core.entity_view_display.node.consultation.diff.yml
- config/uregni/config/core.entity_view_display.node.news.diff.yml
- config/uregni/config/core.entity_view_display.node.webform.diff.yml
Also made small changes to the News and Consultations
> Configure Webform revision comparison view mode

- web/sites/uregni/themes/uregni_theme/templates/block/block--system-main-block.html.twig
Removing content class from blocks as it was causing styling issues and duplicate content classes.
> Removing content class from blocks

- config/uregni/config/structure_sync.data.yml
Changing top level parent items to no link and duplicating below with a name change
> Updates to main menu

- config/uregni/config/views.view.publications_search.yml
- config/uregni/config/views.view.vacancies.yml
Resetting these again as I hadn't fully imported menu links the last time.
> Main menu links

- .circleci/config.yml
- Structural changes to Edge build, now syncs data rather than re-deploying
- Added steps to build Uregni theme
> D8 un 248 part3

- config/uregni/config/core.base_field_override.node.staff_member.title.yml
- config/uregni/config/node.type.staff_member.yml
I have also made the 'Member name' field required to align with D7
> D8UN-276 Change field name on board member form

- .lando/config/solr/7.x/default/schema.xml
- .lando/config/solr/7.x/default/solrconfig.xml
- .platform/solr_config/schema.xml
- .platform/solr_config/solrconfig.xml
Update Solr schema on Lando and on Platform
> update solr schema

- composer.json
- composer.lock
- config/uregni/config/core.extension.yml
- config/uregni/config/facets.facet.date.yml
- config/uregni/config/facets.facet.publication_date_consultation.yml
- config/uregni/config/facets.facet.published_date.yml
- install new facet drilldown contrib module that has been created by the Unity team
- configure consultation, publication and news search facets to use the new module
> Install facet drilldown module

- .platform.app.yaml
- web/modules/custom/unity_common/drush.services.yml
- web/modules/custom/unity_common/src/Commands/UnityDrushCommands.php
- Fix site loop when deploying Unity sites
- Created new drush command to conditionally import blocks, menus & taxonomies
> Multi site loop

- composer.json
- composer.lock
- config/uregni/config/content_lock.settings.yml
- config/uregni/config/content_lock_timeout.settings.yml
- config/uregni/config/core.extension.yml
- web/profiles/unity/nicsdru_unity_profile/config/install/content_lock.settings.yml
- web/profiles/unity/nicsdru_unity_profile/config/install/content_lock_timeout.settings.yml
- web/profiles/unity/nicsdru_unity_profile/nicsdru_unity_profile.info.yml
Adding the content lock module to UREGNI and the install profile for future sites.
> Content lock

- .lando.base.yml
- composer.json
- composer.lock
- Bug fix to Drupal console 
- Pull latest version of date_facet_drilldown module as it correctly handles active year facets when duplicated by the facets_summary module
> D8 un 360 b

- config/hatecrimereviewni/config/core.entity_form_display.paragraph.map.default.yml
- config/hatecrimereviewni/config/core.entity_view_display.paragraph.map.default.yml
- config/hatecrimereviewni/config/core.entity_view_display.paragraph.map.embed.yml
- config/hatecrimereviewni/config/core.entity_view_display.paragraph.map.preview.yml
- config/hatecrimereviewni/config/core.entity_view_mode.paragraph.embed.yml
- config/hatecrimereviewni/config/core.entity_view_mode.paragraph.preview.yml
- config/hatecrimereviewni/config/core.extension.yml
- config/hatecrimereviewni/config/embed.button.map.yml
- config/hatecrimereviewni/config/entity_browser.browser.location_browser.yml
- config/hatecrimereviewni/config/field.field.paragraph.map.field_location.yml
- config/hatecrimereviewni/config/field.storage.paragraph.field_location.yml
- config/hatecrimereviewni/config/geocoder.settings.yml
- config/hatecrimereviewni/config/geolocation_google_maps.settings.yml
- config/hatecrimereviewni/config/paragraphs.paragraphs_type.map.yml
- config/hatecrimereviewni/config/paragraphs.settings.yml
- config/hatecrimereviewni/config/search_api.settings.yml
Config for the google map field. This will be re-usable over all sites I imagine. Should this config also be added to either origins_media or unity install profile?
> Google map field

- config/uregni/config/pathauto.pattern.publications_pattern.yml
Updating publications URL pattern
> D8UN-378 Updating publications URL pattern

- config/hatecrimereviewni/config/core.entity_form_display.node.news.default.yml
- config/hatecrimereviewni/config/core.entity_view_display.node.news.default.yml
- config/hatecrimereviewni/config/core.entity_view_display.node.news.teaser.yml
- config/hatecrimereviewni/config/core.extension.yml
- config/hatecrimereviewni/config/field.field.node.news.field_photo.yml
- config/hatecrimereviewni/config/field.storage.node.field_photo.yml
News settings and enabling media library edit module
> News settings

- .platform.app.yaml
Updating platform cron settings for the multisite configuration.
> Updating platform cron settings

- web/sites/hatecrimereviewni/modules/custom/hatecrimereviewni_migrations/config/install/migrate_plus.migration.upgrade_d7_node_complete_news.yml
- web/sites/hatecrimereviewni/modules/custom/hatecrimereviewni_migrations/config/install/migrate_plus.migration.upgrade_d7_node_complete_page.yml
Amending the files from reference so files are mapped to the right directory
> Amending migration files

- web/modules/custom/unity_map_embed/config/optional/core.entity_form_display.paragraph.map.default.yml
- web/modules/custom/unity_map_embed/config/optional/core.entity_view_display.paragraph.map.default.yml
- web/modules/custom/unity_map_embed/config/optional/core.entity_view_display.paragraph.map.embed.yml
- web/modules/custom/unity_map_embed/config/optional/core.entity_view_display.paragraph.map.preview.yml
- web/modules/custom/unity_map_embed/config/optional/core.entity_view_mode.paragraph.embed.yml
- web/modules/custom/unity_map_embed/config/optional/core.entity_view_mode.paragraph.preview.yml
- web/modules/custom/unity_map_embed/config/optional/embed.button.map.yml
- web/modules/custom/unity_map_embed/config/optional/entity_browser.browser.location_browser.yml
- web/modules/custom/unity_map_embed/config/optional/field.field.paragraph.map.field_location.yml
- web/modules/custom/unity_map_embed/config/optional/field.storage.paragraph.field_location.yml
- web/modules/custom/unity_map_embed/config/optional/paragraphs.paragraphs_type.map.yml
- web/modules/custom/unity_map_embed/unity_map_embed.info.yml
Based on discussion around updating the unity install profile, I have created a module to create the map embed button for CKEditor.
> Create a module to configure the map embed button in CKEditor

- composer.json
- composer.lock
New version needed in order to import new cookie content blocker filter
> Update to latest version of origins_modules

- config/fiscalcommissionni/config/core.entity_form_display.node.basic_page.default.yml
- config/fiscalcommissionni/config/core.entity_view_display.node.basic_page.default.yml
- config/fiscalcommissionni/config/core.entity_view_display.node.basic_page.diff.yml
- config/fiscalcommissionni/config/core.entity_view_display.node.basic_page.teaser.yml
- config/fiscalcommissionni/config/field.field.node.basic_page.field_meta_tags.yml
- config/fiscalcommissionni/config/field.field.node.news.field_published_date.yml
- config/fiscalcommissionni/config/structure_sync.data.yml
- config/fiscalcommissionni/config/system.site.yml
- Add revisions view to basic page content type
- Add meta tags field to basic page
- News published date defaults to today
- Remove full stop from front page heading
- Update menu links
> Fiscal Comm: Miscellaneous config fixes

- config/fiscalcommissionni/config/block.block.mainpagecontent.yml
- config/fiscalcommissionni/config/block.block.pagetitle.yml
- config/fiscalcommissionni/config/block.block.views_block__commissioners_commissioners_block.yml
Add main page content block and place it before the commissioners view block
> D8UN-498 Fiscal Comm: Add main page content block 

- config/fiscalcommissionni/config/eu_cookie_compliance.settings.yml
- config/odscni/config/eu_cookie_compliance.settings.yml
- config/uregni/config/eu_cookie_compliance.settings.yml
- web/profiles/unity/nicsdru_unity_profile/config/install/eu_cookie_compliance.settings.yml
There was a small spelling error on Uregni and Fiscal Comm, also in the install profile. ODSC wasn't up to date.
> D8UN-179 Update Cookie banner on all sites

- .platform/services.yaml
Disk space ran out again on Unity - try to give us some leeway this time !
> increase disk space

- config/odscni/config/core.entity_form_display.node.page.default.yml
- config/odscni/config/core.entity_view_display.node.page.default.yml
- config/odscni/config/core.entity_view_display.node.page.diff.yml
- config/odscni/config/core.entity_view_display.node.page.teaser.yml
- config/odscni/config/core.extension.yml
- config/odscni/config/field.field.node.page.body.yml
- config/odscni/config/field.field.node.page.field_next_audit_due.yml
- config/odscni/config/google_analytics.settings.yml
- config/odscni/local/migrate_drupal.settings.yml
- config/odscni/local/stage_file_proxy.settings.yml
- config/odscni/local/ultimate_cron.job.dblog_cron.yml
- Install allowed_formats
- Set allowed formats to Basic HTML on body field
- Add next audit due field to basic page
> Small changes to odsc

- config/fiscalcommissionni/config/csp.settings.yml
- config/niauditoffice/config/csp.settings.yml
- config/nifiscalcouncil/config/csp.settings.yml
- config/odscni/config/csp.settings.yml
- config/uregni/config/csp.settings.yml
- web/profiles/unity/nicsdru_unity_profile/config/install/csp.settings.yml
> D8UN-520 Update Content Security Policy

- config/niauditoffice/config/core.entity_form_display.node.faq.default.yml
- config/niauditoffice/config/core.entity_view_display.node.publication_page.default.yml
- config/niauditoffice/config/core.entity_view_display.node.staff_member.default.yml
- config/niauditoffice/config/field.field.node.news.body.yml
Some changes I noticed when reviewed node edit forms
> Niao node edit review

- config/fiscalcommissionni/config/views.view.workflow_moderation.yml
- config/niauditoffice/config/core.entity_form_display.node.page.default.yml
- config/niauditoffice/config/core.entity_view_display.node.page.default.yml
- config/niauditoffice/config/core.entity_view_display.node.page.diff.yml
- config/niauditoffice/config/core.entity_view_display.node.page.teaser.yml
- config/niauditoffice/config/field.field.node.page.field_next_audit_due.yml
- config/niauditoffice/config/origins_workflow.auditsettings.yml
- config/niauditoffice/config/views.view.workflow_moderation.yml
- config/nifiscalcouncil/config/views.view.workflow_moderation.yml
- config/odscni/config/views.view.workflow_moderation.yml
- config/uregni/config/views.view.workflow_moderation.yml
- web/profiles/unity/nicsdru_unity_profile/config/optional/views.view.workflow_moderation.yml
I needed to add the next audit due field to the audit office site and configure it so that the view could be configured properly
> D8UN-614 Fix workbench area views on all sites

- .circleci/config.yml
Fixing buster environment change
> Edge build failure

- web/modules/custom/unity_search_pages/unity_search_pages.module
which causes an exception internally in solr.
> Fix incorrectly referenced spellcheck dictionary 

- composer.json
- composer.lock
There is a bug in the EU Cookie compliance module when the pop up banner is positioned at the top. https://www.drupal.org/project/eu_cookie_compliance/issues/3243001
> Patch to fix cookie compliance popup

- config/mahinquiry/config/block.block.contactdetails.yml
- config/mahinquiry/config/structure_sync.data.yml
This kept failing on platform, so hopefully this will fix it permanently.
> MAHI: Configure footer contact block properly

- .circleci/config.yml
> Edge build change

- .platform/routes.yaml
Add new route so that fiscalcommissionni.org site works correctly
> D8 un 1104

- config/nipolicingboard/local/stage_file_proxy.settings.yml
Just noticed that Stage File Proxy wasn't working properly on local dev sites for NI Policing so here is a quick fix
> fix stage file proxy for nipolicingboard

- .platform.app.yaml
> Platform fix

- .circleci/config.yml
Now using a full-fat style container image to prioritise convenience, tools and customisability over image slimness. Pre-compiled PHP extensions and services takes priority over image size. Network bandwidth less of an issue (time + money) over compute time/resource on Circle CU from adding packages and compiling extensions in each pipeline.
> First attempt at using thecodingmachine docker image

- composer.lock
Upgrade unity modules and origins modules
> Unity release 0.31.3

- config/fiscalcommissionni/config/google_analytics.settings.yml
- config/pcsps/config/core.extension.yml
- config/pcsps/production/fastly.settings.yml
- Install Fastly on production PCSPS site
- Correction to GA config for Fiscal Commission
> Production config changes

- composer.lock
> Unity release 0.33.1

- .circleci/config.yml
> Edge build tweaks

- config/niauditoffice/config/core.entity_view_display.node.feature.default.yml
- config/niauditoffice/config/field.field.media.image.field_media_image.yml
- config/niauditoffice/config/views.view.news_search.yml
- config/niauditoffice/config/views.view.publications_search.yml
- config/niauditoffice/config/views.view.search.yml
- config/niauditoffice/config/views.view.slideshow.yml
- config/nipolicingboard/config/core.entity_view_display.node.feature.default.yml
- config/nipolicingboard/config/views.view.slideshow.yml
- config/octf/config/core.entity_view_display.node.feature.default.yml
- config/octf/config/views.view.featured_content.yml
- config/octf/config/views.view.news_search.yml
- config/octf/config/views.view.publications_search.yml
- config/octf/config/views.view.search.yml
- config/pcsps/config/core.entity_view_display.node.feature.default.yml
- config/pcsps/config/views.view.slideshow.yml
- config/uregni/config/core.entity_view_display.node.feature.default.yml
- config/uregni/config/views.view.slideshow.yml
Making the link field unlimited characters in display mode and views as they are being cut off.
> D8 un 1446 link

- .circleci/config.yml
- composer.json
- composer.lock
Hotfix to production after problems on NIAO
> upgrade whatlinkshere

- composer.json
- composer.lock
pulling entityqueue patch from maestro
> D8 un 2364b

- .lando.base.yml
- build-themes.sh
Feature requested by @AdamMcFet 
If it looks good, I can extend to the other two Unity codebases
> Rebuild theme pick site

- project/config/nipolicingboard/config/block.block.followus.yml
- project/config/nipolicingboard/config/nipolicingboard_theme.settings.yml
removed twitter block
added follow us block
added linkedin url
> removed twitter block / added follow us block/ added linkedin url

- composer.json
- composer.lock
U1 reinstate entityqueue patch
> U1 reinstate entityqueue patch

- project/config/nipolicingboard/config/core.entity_form_display.node.page.default.yml
- project/config/nipolicingboard/config/core.entity_view_display.node.page.default.yml
- project/config/nipolicingboard/config/core.entity_view_display.node.page.diff.yml
- project/config/nipolicingboard/config/core.entity_view_display.node.page.teaser.yml
- project/config/nipolicingboard/config/field.field.node.page.field_next_audit_due.yml
- project/config/nipolicingboard/config/field.storage.node.field_next_audit_due.yml
- project/config/nipolicingboard/config/origins_workflow.auditsettings.yml
Added missing config for NIPolicingBoard
> Basic page audit settings

- composer.json
- composer.lock
- project/config/niauditoffice/config/antibot.settings.yml
- project/config/niauditoffice/config/core.extension.yml
- project/config/octf/config/antibot.settings.yml
- project/config/octf/config/core.extension.yml
- project/config/pbni/config/antibot.settings.yml
- project/config/pbni/config/core.extension.yml
- project/config/uregni/config/antibot.settings.yml
- project/config/uregni/config/core.extension.yml
Installing and configuring antibot module for sites that have a webform - Unity 1
> D8UN-2791 

- composer.json
- composer.lock
- Upgrade google_tag module in preparation for Google consent mode
- Pull other upstream changes
> Google consent mode

- composer.json
- composer.lock
Install patches for Drupal core 10.3 upgrade
> Core patches for 10.3

- project/config/attorneygeneralni/config/system.performance.yml
- project/config/cscsreviewni/config/system.performance.yml
- project/config/employmenttribunalsni/config/system.performance.yml
- project/config/fiscalcommissionni/config/system.performance.yml
- project/config/independentreviewofeducation/config/system.performance.yml
- project/config/investnireview/config/system.performance.yml
- project/config/mahinquiry/config/system.performance.yml
- project/config/niauditoffice/config/system.performance.yml
- project/config/nifiscalcouncil/config/system.performance.yml
- project/config/nipolicingboard/config/system.performance.yml
- project/config/octf/config/system.performance.yml
- project/config/odscni/config/system.performance.yml
- project/config/pbni/config/system.performance.yml
- project/config/pcsps/config/system.performance.yml
- project/config/uregni/config/system.performance.yml
- project/config/urologyservicesinquiry/config/system.performance.yml
Turn off js aggregation in order to avoid moderation sidebar problems under core 10.3
> Turn off js aggregation

- composer.lock
This core upgrade is being applied as a hotfix to production
> Drupal core upgrade 10.3.13

- .circleci/config.yml
Edge builds have been timing out
> Increase edge build timeouts to 20 minutes

- composer.lock
> Production release
